<template>
  <v-container>
    <ConsistentMP>
      <h1 id="lorem">{{ getLoremIpsum }}</h1>
      <h3>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</h3>
      <h5>"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."</h5>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend eget ante non dictum. In sagittis nisl sed posuere ullamcorper. Proin finibus porttitor neque nec rutrum. Nulla et iaculis leo. Sed blandit at sapien a hendrerit. Integer porttitor purus a ex condimentum, in rhoncus quam consectetur. Duis lobortis ac odio ac sodales. Morbi vestibulum, eros id commodo ultrices, lorem elit sodales urna, tempus blandit justo nisl id orci. Donec quis eros diam. Duis at ligula finibus, tincidunt ligula sit amet, mollis dolor. Maecenas lobortis non elit at ultricies. Curabitur convallis lectus vitae tellus rhoncus, ac lobortis metus condimentum. Maecenas interdum luctus consectetur. Nunc luctus, velit quis placerat congue, augue sem pellentesque libero, vel condimentum metus nulla sed nulla. Duis eget lacinia ante. Cras blandit interdum eros non tempor.</p>
      <p>In condimentum mauris erat, a ornare diam ornare vel. Phasellus ullamcorper, orci sit amet placerat euismod, ex quam scelerisque libero, nec hendrerit nulla sem id tortor. Morbi ornare massa justo, et vestibulum neque vehicula et. Quisque fringilla, sem non cursus pharetra, neque orci dictum lacus, vitae pellentesque risus neque vitae nibh. Pellentesque ultricies posuere ipsum at pretium. Vivamus sit amet velit nisi. Aliquam nec eros tortor. Vivamus gravida in quam quis aliquam. Aenean condimentum in nisi eu interdum. Sed eleifend imperdiet tellus id blandit. Sed pellentesque, ligula vitae luctus condimentum, augue neque sollicitudin nibh, eu rhoncus turpis magna at sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis euismod blandit dolor, nec semper turpis imperdiet id. Duis eget sollicitudin nisi, non molestie erat. Suspendisse in pretium velit.</p>
      <p>Curabitur nec sodales dui. Phasellus ultrices, erat varius hendrerit tempor, neque massa imperdiet massa, id sollicitudin nisl lacus nec sem. Aenean pellentesque gravida euismod. Aenean sed felis non ligula volutpat consectetur quis rutrum mi. Suspendisse potenti. In ante justo, luctus laoreet libero eu, imperdiet consectetur dui. Vestibulum pulvinar eros luctus diam pulvinar mollis. Vivamus sit amet velit eu nunc malesuada porta. Curabitur ut faucibus dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper mauris sed lectus placerat luctus. Integer ornare ut lectus sit amet egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
      <p>Maecenas dignissim libero nisl, sit amet venenatis velit suscipit in. Phasellus feugiat pellentesque vulputate. Maecenas efficitur, sem eu scelerisque condimentum, lacus lectus iaculis ante, et convallis elit orci quis ipsum. Pellentesque lectus nisl, ullamcorper in vehicula non, facilisis sit amet metus. Donec sed dictum est. Vestibulum blandit erat vitae turpis porta, eu luctus dui elementum. Vivamus scelerisque hendrerit varius. Donec dignissim dolor vel leo lacinia, sit amet pulvinar diam dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel leo vel nisi finibus efficitur gravida nec orci. Suspendisse rhoncus ligula in viverra mollis. Sed auctor felis vel aliquet egestas.</p>
      <p id="cras">Cras ornare odio vel dui pulvinar vestibulum. Integer hendrerit, lacus id efficitur vestibulum, massa elit auctor nulla, nec condimentum felis nisi non dolor. In dictum ut est at ornare. Phasellus felis leo, ornare ac nisi ac, maximus facilisis lacus. Praesent suscipit, ante vel molestie scelerisque, sem magna pretium mi, id vehicula justo quam ac est. Pellentesque dignissim facilisis risus, id tincidunt ante sagittis ac. Duis vehicula non tellus vel imperdiet. Vestibulum eget hendrerit purus, quis ornare eros. Phasellus posuere magna a massa iaculis pellentesque. Phasellus ut consectetur eros. Curabitur bibendum, leo ac lobortis dapibus, nisi neque commodo tortor, eget varius tellus nisl pellentesque ligula. Praesent auctor, ex vel eleifend commodo, nibh ipsum pharetra lorem, ac hendrerit nibh turpis in sem. Proin leo turpis, convallis ut nisi at, efficitur tincidunt leo. Maecenas et pretium purus. Ut est nisl, bibendum sit amet tempus ac, placerat vitae ipsum. Curabitur ultrices fringilla congue.</p>    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend eget ante non dictum. In sagittis nisl sed posuere ullamcorper. Proin finibus porttitor neque nec rutrum. Nulla et iaculis leo. Sed blandit at sapien a hendrerit. Integer porttitor purus a ex condimentum, in rhoncus quam consectetur. Duis lobortis ac odio ac sodales. Morbi vestibulum, eros id commodo ultrices, lorem elit sodales urna, tempus blandit justo nisl id orci. Donec quis eros diam. Duis at ligula finibus, tincidunt ligula sit amet, mollis dolor. Maecenas lobortis non elit at ultricies. Curabitur convallis lectus vitae tellus rhoncus, ac lobortis metus condimentum. Maecenas interdum luctus consectetur. Nunc luctus, velit quis placerat congue, augue sem pellentesque libero, vel condimentum metus nulla sed nulla. Duis eget lacinia ante. Cras blandit interdum eros non tempor.</p>
      <p>In condimentum mauris erat, a ornare diam ornare vel. Phasellus ullamcorper, orci sit amet placerat euismod, ex quam scelerisque libero, nec hendrerit nulla sem id tortor. Morbi ornare massa justo, et vestibulum neque vehicula et. Quisque fringilla, sem non cursus pharetra, neque orci dictum lacus, vitae pellentesque risus neque vitae nibh. Pellentesque ultricies posuere ipsum at pretium. Vivamus sit amet velit nisi. Aliquam nec eros tortor. Vivamus gravida in quam quis aliquam. Aenean condimentum in nisi eu interdum. Sed eleifend imperdiet tellus id blandit. Sed pellentesque, ligula vitae luctus condimentum, augue neque sollicitudin nibh, eu rhoncus turpis magna at sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis euismod blandit dolor, nec semper turpis imperdiet id. Duis eget sollicitudin nisi, non molestie erat. Suspendisse in pretium velit.</p>
      <p>Curabitur nec sodales dui. Phasellus ultrices, erat varius hendrerit tempor, neque massa imperdiet massa, id sollicitudin nisl lacus nec sem. Aenean pellentesque gravida euismod. Aenean sed felis non ligula volutpat consectetur quis rutrum mi. Suspendisse potenti. In ante justo, luctus laoreet libero eu, imperdiet consectetur dui. Vestibulum pulvinar eros luctus diam pulvinar mollis. Vivamus sit amet velit eu nunc malesuada porta. Curabitur ut faucibus dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper mauris sed lectus placerat luctus. Integer ornare ut lectus sit amet egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
      <p id="maecenas">Maecenas dignissim libero nisl, sit amet venenatis velit suscipit in. Phasellus feugiat pellentesque vulputate. Maecenas efficitur, sem eu scelerisque condimentum, lacus lectus iaculis ante, et convallis elit orci quis ipsum. Pellentesque lectus nisl, ullamcorper in vehicula non, facilisis sit amet metus. Donec sed dictum est. Vestibulum blandit erat vitae turpis porta, eu luctus dui elementum. Vivamus scelerisque hendrerit varius. Donec dignissim dolor vel leo lacinia, sit amet pulvinar diam dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel leo vel nisi finibus efficitur gravida nec orci. Suspendisse rhoncus ligula in viverra mollis. Sed auctor felis vel aliquet egestas.</p>
      <p>Cras ornare odio vel dui pulvinar vestibulum. Integer hendrerit, lacus id efficitur vestibulum, massa elit auctor nulla, nec condimentum felis nisi non dolor. In dictum ut est at ornare. Phasellus felis leo, ornare ac nisi ac, maximus facilisis lacus. Praesent suscipit, ante vel molestie scelerisque, sem magna pretium mi, id vehicula justo quam ac est. Pellentesque dignissim facilisis risus, id tincidunt ante sagittis ac. Duis vehicula non tellus vel imperdiet. Vestibulum eget hendrerit purus, quis ornare eros. Phasellus posuere magna a massa iaculis pellentesque. Phasellus ut consectetur eros. Curabitur bibendum, leo ac lobortis dapibus, nisi neque commodo tortor, eget varius tellus nisl pellentesque ligula. Praesent auctor, ex vel eleifend commodo, nibh ipsum pharetra lorem, ac hendrerit nibh turpis in sem. Proin leo turpis, convallis ut nisi at, efficitur tincidunt leo. Maecenas et pretium purus. Ut est nisl, bibendum sit amet tempus ac, placerat vitae ipsum. Curabitur ultrices fringilla congue.</p>
    </ConsistentMP>
  </v-container>
</template>

<script>
import ConsistentMP from './UX/ConsistentMP'
export default {
  name: 'LoremIpsum',
  components: { ConsistentMP },
  computed: {
    getLoremIpsum() {
      return this.$store.getters.getLoremIpsum
    }
  }
}
</script>

<style scoped>

</style>
